set -euo pipefail

MOD_ROOT_DIR="mods/blankStone/files/scripts/biomes/hidden_message"   # where hidden_message_update.lua and orb_NN/ folders live
GLYPH_DIR="mods/blankStone/files/VFX/image_emitters/glyphs/symbole"  # glyph images

TARGET_ID_PLACEHOLDER="TODOstone"
GLYPH_FILE_PLACEHOLDER="TODOstone.png"

# Static ParticleEmitterComponent fields, identical for every emitter.
PARTICLE_LIFETIME_MIN="0.5"
PARTICLE_LIFETIME_MAX="1"
PARTICLE_GRAVITY_Y="0.0"
PARTICLE_RENDER_ON_GRID="1"
PARTICLE_ENABLED="0"

SCRIPT_DIR="${1:-.}"
ROOT_BASE_FILE="$SCRIPT_DIR/hidden_message_root_base.xml"

# So that "orb_*/" expands to nothing (instead of a literal string)
# when no orb folders exist, and same for "*.png" with no matches.
shopt -s nullglob

# --- Generate the shared root base file (holds the LuaComponent, identical for every orb) ---
cat > "$ROOT_BASE_FILE" << EOF
<!-- Auto-generated by generate_orb_xml.sh: do not edit by hand. -->
<Entity>
    <LuaComponent
        script_source_file="$MOD_ROOT_DIR/hidden_message_update.lua"
        execute_every_n_frame="5"
    ></LuaComponent>
</Entity>
EOF
echo "[ok]   wrote $ROOT_BASE_FILE"

# --- Generate each orb_NN.xml ---
for orb_dir in "$SCRIPT_DIR"/orb_*/; do
    orb_dir="${orb_dir%/}"                 # strip trailing slash
    orb_name="$(basename "$orb_dir")"

    # Only match folders literally named 'orb_<digits>'.
    [[ "$orb_name" =~ ^orb_[0-9]+$ ]] || continue

    # Collect PNG files directly inside this orb's folder (orb.aseprite is a
    # source file, not a runtime asset, so it is naturally excluded here).
    png_files=("$orb_dir"/*.png)

    # Build one ParticleEmitterComponent block per PNG found in this orb's folder.
    particle_blocks=""
    for png_path in "${png_files[@]}"; do
        png_file="$(basename "$png_path")"
        material_name="${png_file%.png}"
        particle_blocks+="        <ParticleEmitterComponent
            emitted_material_name=\"$material_name\"
            emit_cosmetic_particles=\"1\"
            image_animation_file=\"$MOD_ROOT_DIR/$orb_name/$png_file\"
            lifetime_min=\"$PARTICLE_LIFETIME_MIN\"
            lifetime_max=\"$PARTICLE_LIFETIME_MAX\"
            gravity.y=\"$PARTICLE_GRAVITY_Y\"
            render_on_grid=\"$PARTICLE_RENDER_ON_GRID\"
            _enabled=\"$PARTICLE_ENABLED\"
        ></ParticleEmitterComponent>
"
    done

    # Only emit the "local images" Entity block if this orb actually has PNGs yet
    # (a few orbs currently only have orb.aseprite, no exported PNG).
    local_images_block=""
    if [ "${#png_files[@]}" -gt 0 ]; then
        local_images_block="    <Entity>
        <InheritTransformComponent></InheritTransformComponent>

        <!-- TODO: set the correct target material id for this orb -->
        <VariableStorageComponent
            name=\"hidden_message_target_id\"
            value_string=\"$TARGET_ID_PLACEHOLDER\"
        ></VariableStorageComponent>

$particle_blocks    </Entity>
"
    fi

    out_file="$orb_dir/$orb_name.xml"
    cat > "$out_file" << EOF
<Entity>

    <Base file="$MOD_ROOT_DIR/hidden_message_root_base.xml" />

    <Entity>
        <InheritTransformComponent></InheritTransformComponent>

        <VariableStorageComponent
            name="hidden_message_target_id"
            value_string="orbPowderStone"
        ></VariableStorageComponent>

        <!-- TODO: point to the correct glyph image for this orb, same directory -->
        <ParticleEmitterComponent
            emitted_material_name="spark_red"
            emit_cosmetic_particles="1"
            image_animation_file="$GLYPH_DIR/$GLYPH_FILE_PLACEHOLDER"
            lifetime_min="$PARTICLE_LIFETIME_MIN"
            lifetime_max="$PARTICLE_LIFETIME_MAX"
            gravity.y="$PARTICLE_GRAVITY_Y"
            render_on_grid="$PARTICLE_RENDER_ON_GRID"
            _enabled="$PARTICLE_ENABLED"
        ></ParticleEmitterComponent>
    </Entity>

$local_images_block</Entity>
EOF

    echo "[ok]   $orb_name: wrote $out_file (${#png_files[@]} local image(s))"
done
